#!/bin/sh
#
# @name Standard VTOL
#
# @type Standard VTOL
#

. ${R}etc/init.d/rc.vtol_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=standard_vtol}

param set-default SIM_GZ_EN 1

param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_BAROSIM 0
param set-default SENS_EN_MAGSIM 1
param set-default SENS_EN_ARSPDSIM 1

param set-default SYS_HAS_NUM_ASPD 0

# TODO: Enable motor failure detection when the
# VTOL no longer reports 0A for all ESCs in SITL
param set-default FD_ACT_EN 0
param set-default FD_ACT_MOT_TOUT 500

param set-default CA_AIRFRAME 2

param set-default COM_PREARM_MODE 2

param set-default CA_ROTOR_COUNT 5

#FR CCW
param set-default CA_ROTOR0_PX 0.44
param set-default CA_ROTOR0_PY 0.45	#0.081
#param set-default CA_ROTOR0_PZ -0.45
param set-default CA_ROTOR0_KM -0.05
#param set-default CA_ROTOR0_TILT 0
#param set-default CA_ROTOR0_CT 100

#BL CCW
param set-default CA_ROTOR1_PX -0.44
param set-default CA_ROTOR1_PY -0.45	#0.081
#param set-default CA_ROTOR1_PZ 0.45
param set-default CA_ROTOR1_KM -0.05
#param set-default CA_ROTOR1_TILT 0
#param set-default CA_ROTOR1_CT 100

#FL CW
param set-default CA_ROTOR2_PX -0.44
param set-default CA_ROTOR2_PY 0.45	#0.081
#param set-default CA_ROTOR2_PZ 0.45
param set-default CA_ROTOR2_KM 0.05
#param set-default CA_ROTOR2_TILT 0
#param set-default CA_ROTOR2_CT 100

#BR CW
param set-default CA_ROTOR3_PX 0.44
param set-default CA_ROTOR3_PY -0.45	#0.081
#param set-default CA_ROTOR3_PZ -0.45
param set-default CA_ROTOR3_KM 0.05
#param set-default CA_ROTOR3_TILT 0
#param set-default CA_ROTOR3_CT 100

#Puller
param set-default CA_ROTOR4_PX 0.526
param set-default CA_ROTOR4_PY 0
param set-default CA_ROTOR4_AX 1
param set-default CA_ROTOR4_KM 0.05
param set-default CA_ROTOR4_TILT 0
param set-default CA_ROTOR4_CT 100

#SIM_GZ ESC Failsafe Value 
param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_MIN1 10
param set-default SIM_GZ_EC_MAX1 1150
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_MIN2 10
param set-default SIM_GZ_EC_MAX2 1150
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_MIN3 10
param set-default SIM_GZ_EC_MAX3 1150
param set-default SIM_GZ_EC_FUNC4 104
param set-default SIM_GZ_EC_MIN4 10
param set-default SIM_GZ_EC_MAX4 1150

param set-default SIM_GZ_EC_FUNC5 105
param set-default SIM_GZ_EC_MIN5 0
param set-default SIM_GZ_EC_MAX5 3500

#SIM_GZ Servo Failsafe Value 
param set-default SIM_GZ_SV_FUNC1 201
param set-default SIM_GZ_SV_FUNC2 202
param set-default SIM_GZ_SV_FUNC3 203
param set-default SIM_GZ_SV_FUNC4 204

#RC control input mode (A value of 0 enables RC transmitter control (only). A valid RC transmitter calibration is required. A value of 1 allows joystick control only.)
param set-default COM_RC_IN_MODE 0

#Total number of Control Surfaces Values
param set-default CA_SV_CS_COUNT 4
param set-default CA_SV_CS0_TYPE 1 #Left Aileron
param set-default CA_SV_CS0_TRQ_R -0.5
param set-default CA_SV_CS1_TYPE 2 #Right Aileron
param set-default CA_SV_CS1_TRQ_R 0.5
param set-default CA_SV_CS2_TYPE 3 #Elevator
param set-default CA_SV_CS2_TRQ_P 1
param set-default CA_SV_CS3_TYPE 4 #R
param set-default CA_SV_CS3_TRQ_P 1


param set-default ATT_BIAS_MAX 1
#Avoids limit cycling from a too aggressively tuned period/damping combination.
#param set-default NPFG_PERIOD 10.0

#param set-default GPS_PITCH_OFFSET 10
#param set-default GPS_YAW_OFFSET -4.5

#Pitch rate feed forward 
#param set-default FW_PR_FF 0.2		#0.2		0.5

#Pitch rate proportional gain 
#param set-default FW_PR_P 0.9		#0.9		0.09

#Pitch setpoint offset (pitch at level flight)
param set-default FW_PSP_OFF 2	#[-90.0, 90.0] (0.5)

#Minimum pitch angle 
#param set-default FW_P_LIM_MIN -15

#Roll rate feed forward 
#param set-default FW_RR_FF 0.1

#Roll rate proportional gain 
#param set-default FW_RR_P 0.3

#Trim throttle 
#param set-default FW_THR_TRIM 0.25

#Throttle limit max 
#param set-default FW_THR_MAX 0.6

#Throttle limit min 
#param set-default FW_THR_MIN 0.05

#Maximum climb rate 
#param set-default FW_T_CLMB_MAX 8

#Maximum descent rate 
#param set-default FW_T_SINK_MAX 2.7

#Minimum descent rate 
#param set-default FW_T_SINK_MIN 2.2

#The air-mode enables the mixer to increase the total thrust of the multirotor in order to keep attitude and rate control even at low and high throttle. This function should be disabled during tuning as it will help the controller to diverge if the closed-loop is unstable (i.e. the vehicle is not tuned yet). Enabling air-mode for yaw requires the use of an arming switch.
#param set-default MC_AIRMODE 0  #1	0

#param set-default EKF2_REQ_NSATS 6

#Roll rate proportional gain, i.e. control output for angular speed error 1 rad/s.

param set-default MC_ROLL_P 0.8		#[0.0, 12] (0.1)
param set-default MC_ROLLRATE_P 0.01	#[0.01, 0.5] (0.01)
param set-default MC_ROLLRATE_I 0.01	#[0.0, ?] (0.01)
param set-default MC_ROLLRATE_FF 0.01	#[0.0, ?] 
param set-default MC_ROLLRATE_D 0.005	#[0.0, 0.01] (0.0005)
param set-default MC_ROLLRATE_MAX 4
param set-default MC_ROLLRATE_K 0.0005	#[0.01, 5.0] (0.0005)

param set-default MC_PITCH_P 0.1		#[0.0, 12] (0.1)
param set-default MC_PITCHRATE_P 0.01	#0.2  [0.01, 0.6] (0.01)
param set-default MC_PITCHRATE_I	0.02 	#[0.0, ?] (0.01)
param set-default MC_PITCHRATE_FF 0.03	#[0.0, ?]
param set-default MC_PITCHRATE_D 0.0005	#[0.0, ?] (0.0005)
param set-default MC_PITCHRATE_MAX 1
param set-default MC_PITCHRATE_K 0.01	#[0.01, 5.0] (0.0005)

param set-default MC_YAW_P 0.1		#[0.0, 5] (0.1) 0.1
param set-default MC_YAWRATE_P 0.05	#0.2  [0.0, 0.6] (0.01) 0.5
param set-default MC_YAWRATE_I 0.04	#[0.0, ?] (0.01)
param set-default MC_YAWRATE_FF 0.01	#[0.0, ?] (0.01)
param set-default MC_YAWRATE_D 0.01	#[0.0, ?] (0.01)
param set-default MC_YAWRATE_MAX 2
param set-default MC_YAWRATE_K 0.001	#[0.0, 5.0] (0.0005)


#Default take-off altitude 
param set-default MIS_TAKEOFF_ALT 10	#10		2.5

#Defined as corrective velocity in m/s per m position error
param set-default MPC_XY_P 0.8

#Defined as corrective acceleration in m/s^2 per m/s velocity error
param set-default MPC_XY_VEL_P_ACC 0.5

#Defined as correction acceleration in m/s^2 per m velocity integral Allows to eliminate steady state errors in disturbances like wind.
param set-default MPC_XY_VEL_I_ACC 4

#Defined as corrective acceleration in m/s^2 per m/s^2 velocity derivative
param set-default MPC_XY_VEL_D_ACC 0.1

#Acceptance Radius 
param set-default NAV_ACC_RAD 5

#Use fixed-wing actuation in hover to accelerate forward (4: Enabled constantly)
param set-default VT_FWD_THRUST_EN 0

#Target throttle value for the transition to fixed-wing flight
param set-default VT_F_TRANS_THR 0.75

#VTOL Type (2: Standard)
param set-default VT_TYPE 2

#Enable checks on ESCs that report their arming state 
param set-default FD_ESCS_EN 0
